SUPERMARKETS = [
    'REWE',
    'SPAR',
    'MARKS&SPENCER',
    'EUROSPAR',
    'ASDA',
    'LIDL',
    'EDEKA',
    'TESCO',
    'DENNS',
    'FRISCHEPARADIES',
    'NETTO',
    'A TASTE OF SPAIN',
    'E REICHELT',
    'CRAWFORDS',
    'KAUFLAND',
    'GETRANKE HOFFMANN',
    'ALDI',
    'MITTE MEER',
    'PENNY',
    'CENTRO ITALIA',
    'ALNATURA',
    'CHILI & PAPRIKA',
    'SUPERCOR',
    'MCATAMNEYS',
    'TEGUT'

]

SHOPPING = [
    'DM-DROGERIE',
    'HEATONS',
    'HOLLAND & BARRETT',
    'DUNNES',
    'OBI',
    'AMAZON',
    'ACTION',
    'WOOLWORTH',
    'AMZN',
    'MCPAPER',
    'ERNSTING',
    'THALIA',
    'C&A',
    'DECATHLON',
    'WH SMITH',
    'DM DROGERIE',
    'EASON',
    'LIBROS',
    'PFENNIGPFEIFFER',
    'ZALANDO',
    'CAMP4',
    'BOOTS',
    'MOORES',
    'TRESPASS',
    'APPLE.COM',
    'MEDIMAX',
    'ARCADEN APOTHEKE',
    'NEWSRAIL CONNOLLY',
    'DEICHMANN',
    'SPORTSDIRECT',
    'SHOE4YOU',
    'FAIRHILL',
    'APCOA',
    'SATURN'
]

TRAVEL = [
    'RYANAIR',
    'LOOP T1',
    'BVG',
    'WESHARE',
    'AERLING',
    'IBERIAEXPRESS',
    'TRANSLINK',
    'MILES',
    'AIR FRANCE',
    'TIER',
    'BUS ATHA CLIATH',
    'NATIONAL EXPRESS',
    'DB Vertreib',
    'FLUGHAFEN',
    'FERNVERKEHR',
    'FRANKFURT MAIN HBF',
    'BOOKING',
    'OPODO',
    'DB VERTRIEB',
    'FRANKFURT M MESSE',
    'HOTEL MEMPHIS'
]

SUBSCRIPTIONS = [
    'GROVER',
    'Telefonica',
    'GOOGLE',
    'WHOOP',
    'SPOTIFY',
    'LINKEDIN',
    'Factory'
]

SERVICES = [
    'TK',
    'Techniker Krankenkasse'
    'VATTENFALL',
    'VOLKSWOHL',
    'SITEGROUND',
    'Finanzamt',
    'ARAG',
    'SKYPE',
    'ENVATO',
    'DEEPL',
    'POST OFFICE',
    'APOTHEKE',
    'SPECSAVERS',
    'Jark',
    'VATTENFALL',
    'MAYD'
]
ENTERTAINMENT = [
    'BARN',
    'COFFEE',
    'CAFFE',
    'WOLT',
    'TOMMIS BURGER JOINT',
    'FADE STREET SOCIAL',
    'CASTLE',
    'VAGABUND',
    'MANEKI JAPANESE',
    'COFFEEANGEL',
    'LOST AND FOUND',
    'ARDTARA',
    'NI CHO',
    'ENZO',
    'BRUTON HOSPITALITYGMBH',
    'JACQUES',
    'ESPRESSO',
    'DUNKIN DONUTS',
    'BONANZA',
    'WALDBUEHNE',
    'EVENTIM',
    'OSLO KAFFEBAR',
    'WEINMARIE',
    'TORTILLERIA MEXA',
    'WOODCUTTER',
    'WALSH',
    'MELS CHIPPY',
    'CONNOLLY BARS',
    'VILLAGE KITCHEN',
    'CHEQUERS',
    'CAF 3121',
    'DUNCAIRN WINES',
    'PREEDA',
    'HOME',
    'BRLO',
    'STATION FOOD',
    'FISH & CHIPS',
    'URSA MINOR',
    'SALSA MEXICAN FOOD',
    'MIDDLETOWN',
    'KOLUMBIENKAFFE',
    'CAFE',
    'BACKWERK',
    'ALTER KRUG DAHLEM',
    'WEINHANDLUNG',
    'WEINBERG',
    'PASTERNAK',
    'BAD SAAROW KUR',
    '19GRAMS',
    'MARKET QUEVEDO',
    'MARKET AGUILERA',
    'HEINEMANN DUTY',
    'HOFLADEN KLAISTOW',
    'ZOLLHAUS PANKOW',
    'BLAUE ADRIA',
    'STEINECKE',
    'HALLESCHES',
    'MIKKELLER',
    'CHILINH',
    'TOYOKO INN',
    'CAFELIX',
    'THAI SNACK',
    'SALT N BONE',
    'ASHLING',
    'PFEFFERHAUS',
    'SICILIAN ICE',
    'MARAFADO PT',
    'TOYOKO INN',
    'BLOCK HOUSE',
    'FAIRLEYS',
    'MALDRON',
    'LIEBLINGS',
    'RESTAURANT',
    'MOTEL ONE',
    'BERLVIN'
]
